clients.bar.defaultHeaders:
  X-Client-ID: bar
clients.bar.ip: 127.0.0.1
clients.bar.port: 4001
clients.bar.timeout: 10000
envVarsToTagInRootScope: []
http.defaultHeaders:
  Accept: application/json
  Content-Type: application/json
http.port: 7783
http.clients.requestUUIDHeaderKey: x-request-uuid
logger.fileName: /var/log/selective-gateway/selective-gateway.log
logger.output: disk
metrics.serviceName: selective-gateway
metrics.m3.includeHost: true
service.env.config: {}
serviceName: selective-gateway
sidecarRouter.default.grpc.ip: 127.0.0.1
sidecarRouter.default.grpc.port: 4998
sidecarRouter.default.http.calleeHeader: RPC-Service
sidecarRouter.default.http.callerHeader: RPC-Caller
sidecarRouter.default.http.ip: 127.0.0.1
sidecarRouter.default.http.port: 4999
sidecarRouter.default.tchannel.ip: 127.0.0.1
sidecarRouter.default.tchannel.port: 5000
tchannel.port: 7784
tchannel.processName: selective-gateway
tchannel.serviceName: selective-gateway
tchannel.clients.requestUUIDHeaderKey: x-request-uuid
useDatacenter: false
clients.baz.alternates:
  routingConfigs:
    - headerName: x-container
      headerValue: ^sandbox$
      serviceName: basicSandbox
      rd: reverse-proxy
    - headerName: x-test-env
      headerValue: ^sandbox$
      serviceName: nomatch
  servicesDetail:
    basicSandbox:
      ip: 127.0.0.1
      port: 8113
    nomatch:
      ip: 127.0.0.1
      port: 8114
grpc.clientServiceNameMapping:
  echo: echo
router.whitelistedPaths:
  - /path/whitelisted
circuitbreaking-configurations:
  levels:
    '1': '0-99'
    '2': '100-999'
    '3': '1000-9999'
    '4': '10000+'
  parameters:
    'default':
      sleepWindowInMilliseconds: 5000
      errorPercentThreshold: 20
      requestVolumeThreshold: 20
      maxConcurrentRequests: 20
    '1':
      sleepWindowInMilliseconds: 7000
      errorPercentThreshold: 10
      requestVolumeThreshold: 15
      maxConcurrentRequests: 20
    '2':
      sleepWindowInMilliseconds: 4000
      errorPercentThreshold: 15
      requestVolumeThreshold: 22
      maxConcurrentRequest: 20
    '3':
      sleepWindowInMilliseconds: 3000
      errorPercentThreshold: 25
      requestVolumeThreshold: 24
      maxConcurrentRequests: 25
    '4':
      sleepWindowInMilliseconds: 1000
      errorPercentThreshold: 30
      requestVolumeThreshold: 25
      maxConcurrentRequests: 30